### ISSUE TITLE
fix: define and/or use an existing type for GitHubEventAction

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/opensource#34]
Currently, `GitHubEventAction` uses an `any` prop for the payload:

https://github.com/uclaacm/opensource/blob/87b2993fe00ccea7545d403ec9a2a4b918d800e3/components/GitHubEventAction.tsx#L5-L8

This shouldn't have to be the case, since [`octokit`](https://github.com/octokit/octokit.js) defines types for all of its request/responses, including the payload of an API hit. The reason I haven't done this yet? It's hard to find!

So, let's:

1. find the type, and/or create a TS Union of the relevant types
2. simplify the existing code in `GitHubEventAction` to use the new type, and avoid unnecessary `null` / `?` checks

**Comment by reginawang3495** [comment]
@mattxwang oops there is no accurate schema https://github.com/octokit/webhooks/pull/602#issuecomment-1005936266 😓. Webhooks is pretty accurate, so I think we can use that for now esp since Nick has been doing some really great work with it, and slight type issues aren't the end of the world. 

We can update this once they have an events types up  + DM me if you have other thoughts?
